import { elements } from './elements/index.js';

export const group_project_members = {
  "elements": elements,
  "properties": {
    "height": 0,
    "left": 0,
    "top": 0,
    "width": 0,
    "zindex": 22,
    "border_color": "rgba(var(--color_primary_contrast_default_rgb), 0.15)",
    "border_roundness": 0,
    "is_visible": true,
    "vertical_centering": true,
    "background_style": "none",
    "bgcolor": "rgba(var(--color_primary_contrast_default_rgb), 0.05)",
    "border_style": "none",
    "order": 3,
    "row_gap": 20,
    "use_gap": true,
    "fit_width": false,
    "fit_height": true,
    "single_width": false,
    "single_height": false,
    "horiz_alignment": "flex-start",
    "container_layout": "column",
    "collapse_when_hidden": true
  },
  "type": "Group",
  "id": "bTJjz",
  "current_parent": "bTIPd",
  "default_name": "Group A",
  "name": "Group Project Members",
  "style": "Group_transparent_",
};
