import { elements } from './elements/index.js';

export const gf_organizations = {
  "elements": elements,
  "properties": {
    "height": 280,
    "left": 0,
    "top": 0,
    "width": 280,
    "zindex": 13,
    "boxshadow_horizontal": 0,
    "border_roundness": 10,
    "boxshadow_style": "none",
    "vertical_centering": true,
    "background_style": "none",
    "bgcolor": "var(--color_bTGzr_default)",
    "boxshadow_blur": 2,
    "boxshadow_color": "var(--color_bTHBQ_default)",
    "order": 9,
    "reference": "bTPuB",
    "fit_height": true,
    "offset_left": -6,
    "padding_top": 8,
    "padding_left": 8,
    "single_width": false,
    "max_width_css": "290px",
    "min_width_css": "290px",
    "padding_right": 8,
    "single_height": false,
    "padding_bottom": 8,
    "horiz_alignment": "flex-start",
    "container_layout": "column",
    "collapse_when_hidden": true
  },
  "type": "GroupFocus",
  "id": "bTPuN",
  "current_parent": "bTHpR",
  "default_name": "GroupFocus B",
  "name": "GF Organizations",
};
