import { id_to_path } from './id_to_path/index.js';
import { issues_list } from './issues_list/index.js';

export const _index = {
  "id_to_path": id_to_path,
  "issues_list": issues_list,
  "issues_sub": {
    "AAD": "[]",
    "AAL": "[\"bTGyM0\",\"bTHDH\"]",
    "AAU": "[\"bTGky\"]",
    "ACq": "[]",
    "AFm": "[]",
    "AId": "[]",
    "api": "[]",
    "bTGMI": "[]",
    "bTGYf": "[]",
    "bTGbD": "[]",
    "bTGiL": "[]",
    "bTGkE": "[]",
    "bTGpD": "[]",
    "bTHDZ": "[]",
    "bTHLT": "[]",
    "bTHNK": "[]",
    "bTHaX": "[]",
    "bTHjd": "[]",
    "bTHoP": "[\"bTIgg\",\"bTPuN\",\"bThZl\",\"bTHpZ\",\"bTHpk\",\"bTIJj0\",\"bTIJu0\",\"bTIQd\",\"bTIVo\",\"bTIYQ\",\"bTIZA\",\"bTIag\",\"bTIaz\",\"bTIbc\",\"bTIho\",\"bTIkc0\",\"bTInt0\",\"bTIpb0\",\"bTIxF\",\"bTJAw\",\"bTJFX\",\"bTJVH\",\"bTJVR\",\"bTJVv\",\"bTJYq\",\"bTJYx\",\"bTJgz\",\"bTKOx\",\"bTKlb0\",\"bTNjd\",\"bTPun\",\"bTPuy\",\"bTQFk\",\"bTQWL0\",\"bTYEs\",\"bTYPB0\",\"bTcOr\",\"bThxb\",\"bThxm\",\"bThxt\",\"bTiQi\",\"bTidM\",\"bTieB\",\"bTieJ\",\"bTieZ\",\"bTiem\",\"bTitT3\",\"bTitf3\",\"bTits3\",\"bTjEY1\",\"bToTj\",\"bTqKN2\",\"bTqSp2\",\"bTqox\",\"bTtyK\",\"bTuGz0\",\"bTutV1\",\"bTuth1\",\"bTutt1\",\"bTuvA1\",\"bTvDj1\",\"bTwNn\",\"bTwSp\",\"bTxEb1\",\"bTxQV\",\"bTxyL\"]",
    "bTHsj": "[\"bTHsl\",\"bTHsx\",\"bTHta\",\"bTHtn\",\"bTHuR\",\"bTVEr\"]",
    "bTIHA": "[]",
    "bTIcH": "[]",
    "bTJIo": "[\"bTJIt\",\"bTJJH\",\"bTJJL\",\"bTJJk\",\"bTJJp\",\"bTJJr\",\"bTJJw\",\"bTJKC\",\"bTJKI\",\"bTJKO\",\"bTJKg\",\"bTJMB\"]",
    "bTJWI": "[\"bTJWN\",\"bTJWb\",\"bTJrr\",\"bTJsV\",\"bTKEP1\",\"bTJWf\",\"bTJXE\",\"bTJXJ\",\"bTJXL\",\"bTJXQ\",\"bTKEt1\",\"bTKFB1\",\"bTKFM1\",\"bTKFw1\",\"bTJYA\",\"bTJit\",\"bTJXv\",\"bTJXt\",\"bTJXi\",\"bTJXc\",\"bTJXW\"]",
    "bTJjV": "[\"bTJjX\",\"bTJjK\",\"bTYHJ1\",\"bTbBP0\",\"bTJkk\",\"bTJkw\",\"bTJlI\",\"bTJlV\",\"bTJmJ\",\"bTJmR\",\"bTJqL\",\"bTJst\",\"bTMAk\",\"bTYJr1\",\"bTYKC1\",\"bTYKN1\",\"bTYKb1\",\"bTYKl1\",\"bTYLD1\",\"bTYUJ0\",\"bTaxB\",\"bTbBD0\",\"bTbBl0\",\"bTbBt0\",\"bTbCE0\",\"bToWc0\",\"bToXA0\"]",
    "bTJtp": "[\"bTJtr\",\"bTJxD\",\"bTJzB\",\"bTLsV\",\"bTJvc\",\"bTJwL\",\"bTJwS\",\"bTJwY\",\"bTJwv\",\"bTJxt\",\"bTJyE\",\"bTJyP\",\"bTJzY\",\"bTJzj\",\"bTJzr\",\"bTLoA\",\"bTLoM\",\"bTQDs\",\"bTZCB\",\"bTZDO\",\"bTZDV\",\"bTcfE0\",\"bTcfL0\"]",
    "bTKPI": "[\"bTKTX\",\"bTPtZ\",\"bTQXB0\",null,null,null,\"bTKRX\",\"bTKRd\",\"bTKSb\",\"bTKSz\",\"bTKUB\",\"bTKUM\",\"bTKUX\",\"bTKVn0\",\"bTKWP0\",\"bTPWN\",\"bTPZN\",\"bTPZr\",\"bTPZz\",\"bTPbZ\",\"bTPbk\",\"bTPcJ\",\"bTPrg\",\"bTPrt\",\"bTPtH\",\"bTQBo0\",\"bTQFX\",\"bTQIk0\",\"bTQIv0\",\"bTQJD0\",\"bTQJZ0\",\"bTQKE0\",\"bTQLG0\",\"bTQMz0\",\"bTQWv0\",\"bTQXd0\",\"bTQXq0\",\"bTYVM0\",\"bTnee2\",\"bTngi2\",\"bTtML1\",\"bTwxx\",\"bTwyi\",\"bTxQj\",\"bTxTb\",\"bTxUv0\",\"bTxZi\",\"bTxbx\",\"bTxaG0\",\"bTxxo\",\"bTymr\",\"bTymz\"]",
    "bTLPj": "[]",
    "bTLgB": "[\"bTLgD\"]",
    "bTMGw": "[\"bTNqg\",\"bTdrj2\",\"bTnwL2\",\"bTMKl\",\"bTOBT\",\"bTOBk\",\"bTOXZ0\",\"bTOdI0\",\"bTOda0\",\"bTOdn0\",\"bTOdy0\",\"bTOeQ0\",\"bTOwi0\",\"bTOxF0\",\"bTaEG\",\"bTcij\",\"bTciu\",\"bTcjF\",\"bTcjN\",\"bTcjY\",\"bTcjr\",\"bTckI\",\"bTckT\",\"bTcqN\",\"bTcqU\",\"bTdsb2\",\"bTdsl2\",\"bTdss2\",\"bTdsz2\",\"bTdtL2\",\"bTiKb2\",\"bTiKj2\",\"bTiMn2\",\"bTidS2\",\"bTnUz1\",\"bTvue2\"]",
    "bTNcF": "[\"bTNcK\",\"bTNct\",\"bTNfj\",\"bTNgd\",\"bTNeZ\",\"bTNel\"]",
    "bTNuQ": "[]",
    "bTPBZ": "[\"bTPBf\"]",
    "bTPBr": "[\"bTPBs\",\"bTPBt\"]",
    "bTPRh": "[\"bTPRi\",\"bTPRn\",\"bTPSL\"]",
    "bTTMs": "[]",
    "bTTiD": "[]",
    "bTXII": "[]",
    "bTYRt": "[\"bTYRv\",\"bTmQx3\",\"bTmRP3\",\"bTmRZ3\"]",
    "bTYWm": "[\"bTYWn\"]",
    "bTYbX": "[]",
    "bTZAT": "[\"bTZAV\",\"bTZAf\",\"bTZAa\"]",
    "bTZEL": "[]",
    "bTZfD": "[]",
    "bTaEk": "[]",
    "bTaiS": "[]",
    "bTauk": "[\"bTavH\",\"bTavf\",\"bTawp\",\"bTayN\",\"bTayV\"]",
    "bTbex": "[]",
    "bToHK": "[\"bToHP\"]",
    "bTqqe": "[\"bTqrT\",\"bTqqp\"]",
    "bTwll": "[]",
    "bTwln": "[\"bTwlr\",\"bTwlx\",null,null,null,null,\"bTwmF\",\"bTwmK\",\"bTwmo\",\"bTxcv\",\"bTynJ\"]",
    "bTGnB0": "[]",
    "bTGrh1": "[]",
    "bTGto1": "[]",
    "bTGuC1": "[]",
    "bTHFR0": "[]",
    "bTHTh0": "[]",
    "bTHsf0": "[]",
    "bTHxc0": "[]",
    "bTIml0": "[\"bTImr0\",\"bTInQ0\",\"bTIsO0\",\"bTKtI0\",\"bTInX0\",\"bTIqK0\",\"bTIqb0\",\"bTIqi0\",\"bTIss0\",\"bTItD0\",\"bTItL0\",\"bTIuH0\",\"bTIuS0\",\"bTIup0\",\"bTKts0\",\"bTKwT\",\"bTKwn\",\"bTKxj\",\"bTKzr\",\"bThQn\",\"bThQt\",\"bThyz\",\"bThzM\",\"bThzd\",\"bThzp\",\"bTiAC\",\"bTuvj1\",\"bTuvw1\",\"bTuwI1\",\"bTuwV1\",\"bTuyA1\",\"bTvIr1\",\"bTvJR1\"]",
    "bTKGV0": "[]",
    "bTKWz0": "[\"bTKXB0\",\"bTKXL0\",\"bTMFV\"]",
    "bTKdH0": "[\"bTKdM0\",\"bTLDX\",\"bTLFs\",\"bTLuL\",\"bTnqf\",\"bTwKB2\",\"bTKfX0\",\"bTKgN0\",\"bTKin0\",\"bTKjr0\",\"bTKlJ0\",\"bTKmM0\",\"bTLBF\",\"bTLCH\",\"bTLFZ\",\"bTLFh\",\"bTLGW\",\"bTLGh\",\"bTLGp\",\"bTLHF\",\"bTLHM\",\"bTLuq\",\"bTYMN0\",\"bTYZy\",\"bTYaV\",\"bTcPI\",\"bTcPt\",\"bTiFl\",\"bTnqx\",\"bTnrI\",\"bTsrX2\",\"bTsrf2\",\"bTvDt1\",\"bTvIJ1\",\"bTvIU1\",\"bTvJD1\",\"bTwKl2\",\"bTwKy2\"]",
    "bTMVB0": "[]",
    "bTMkN0": "[]",
    "bTNNn0": "[]",
    "bTOCH0": "[\"bTOEj0\",\"bTOFy0\",\"bTOGE0\",\"bTOGK0\",\"bTOGo0\",\"bTOHH0\",\"bTOIH0\",\"bTYUt0\"]",
    "bTOpg0": "[\"bTOpl0\",\"bTOqR0\",\"bTOtV0\",\"bTOuv0\",\"bTOrx0\",\"bTOsC0\",\"bTOsH0\",\"bTOst0\",\"bTOre0\",\"bTOtu0\",\"bTOuF0\",\"bTOuN0\",\"bTOvh0\",\"bTOwK0\",\"bTQQb0\",\"bTYVB0\",\"bTaDt\"]",
    "bTPYM0": "[]",
    "bTQYT0": "[]",
    "bTUdV0": "[\"bTUjC0\",\"bTUjB0\",\"bTUkc0\",\"bTUkv0\",\"bTUlk0\",\"bTUjN0\",\"bTbfB0\",\"bTiRL1\",\"bTqaj1\",\"bTuEb0\",\"bTuHz1\",\"bTukZ1\",\"bTvQr\",\"bTUhW0\",\"bTxOM\",\"bTUor0\",\"bTUow0\",\"bTUpC0\",\"bTUpH0\",\"bTUqd0\",\"bTUqL0\",\"bTUqQ0\",\"bTUqW0\",\"bTUqb0\",\"bTUqn0\",\"bTUqp0\",\"bTUqv0\",\"bTUrB0\",\"bTUrH0\",\"bTUrR0\",\"bTUrZ0\",\"bTUrl0\",\"bTUrr0\",\"bTUsH0\",\"bTUsJ0\",\"bTUsU0\",\"bTUsa0\",\"bTUsg0\",\"bTUsn0\",\"bTUst0\",\"bTUtF0\",\"bTUtW0\",\"bTUti0\",\"bTUto0\",\"bTUtt0\",\"bTUtD0\",\"bTUtz0\",\"bTUuB0\",\"bTUuG0\",\"bTUuL0\",\"bTUuN0\",\"bTUuk0\",\"bTUwR0\",\"bTUwc0\",\"bTUwz0\",\"bTUyC0\",\"bTUvZ0\",\"bTUvg0\",\"bTUvn0\",\"bTUvy0\",\"bTUwD0\",\"bTVAf0\",\"bTVEI0\",\"bTVPF\",\"bTVZJ\",\"bTVab\",\"bTXEp0\",\"bTXHN\",\"bTYIE1\",\"bTYIv\",\"bTYMX\",\"bTYMf\",\"bTYUW0\",\"bTYVR0\",\"bTacv0\",\"bTcIL\",\"bTcLF\",\"bTcKR\",\"bTcXp\",\"bTiHi1\",\"bTiHt1\",\"bTiSn1\",\"bTiVN1\",\"bTjCH\",\"bTnWa0\",\"bTnWy0\",\"bTnXL0\",\"bTnXv0\",\"bTnYF0\",\"bTnYe0\",\"bTnYl0\",\"bTnZH0\",\"bTnZZ0\",\"bTnZt0\",\"bTnaJ0\",\"bTnaX0\",\"bTndi0\",\"bTqID1\",\"bTqaz1\",\"bTqbH1\",\"bTrGZ0\",\"bTrTb2\",\"bTsRf0\",\"bTsVJ\",\"bTspN0\",\"bTtKP\",\"bTtMv0\",\"bTtNN0\",\"bTtNr0\",\"bTtZl\",\"bTtel0\",\"bTtex0\",\"bTtfH0\",\"bTtgP0\",\"bTtgt0\",\"bTthR0\",\"bTthY0\",\"bTtiV0\",\"bTtkT\",\"bTtkk\",\"bTtqH1\",\"bTtsd0\",\"bTtsn0\",\"bTttd0\",\"bTttr0\",\"bTtry1\",\"bTtwL\",\"bTuAm0\",\"bTuEv0\",\"bTuFL0\",\"bTuIf1\",\"bTuIq1\",\"bTuJN1\",\"bTunO1\",\"bTunV1\",\"bTuns1\",\"bTunz1\",\"bTuoL1\",\"bTuob1\",\"bTupe1\",\"bTupv1\",\"bTuqC1\",\"bTuqJ1\",\"bTuqZ1\",\"bTuqg1\",\"bTuvM1\",\"bTuvX1\",\"bTuxD1\",\"bTuyN1\",\"bTuyd1\",\"bTuyk1\",\"bTuzl1\",\"bTvAJ1\",\"bTvAX1\",\"bTvBZ1\",\"bTvCZ1\",\"bTvCn1\",\"bTvCx1\",\"bTvDJ1\",\"bTvEF1\",\"bTvEM1\",\"bTvET1\",\"bTvEd1\",\"bTvFD1\",\"bTvFa1\",\"bTvFr1\",\"bTvGE1\",\"bTvGV1\",\"bTvGn1\",\"bTvHF1\",\"bTvHX1\",\"bTvIf1\",\"bTvQe0\",\"bTvSQ\",\"bTvSb\",\"bTvXH1\",\"bTvaP\",\"bTvkn1\",\"bTvvV2\",\"bTvxR1\",\"bTvxv1\",\"bTvya1\",\"bTwGS\",\"bTwQD5\",\"bTxNQ\",\"bTxNX\",\"bTxOF\",\"bTxdk\",\"bTxgF\",\"bTyQw0\",\"bTUyn0\"]",
    "bTVdc0": "[]",
    "bTWJf0": "[]",
    "bTWgR0": "[]",
    "bTXfj0": "[]",
    "bTbDp0": "[\"bTbDr0\",\"bTbdn0\",\"bTiDP\",\"bTbeH0\",\"bTbej0\",\"bTiDx\",\"bTiEF\",\"bTiEP\",\"bTiGD\",\"bTiKR\",\"bTicc\",\"bTicn\"]",
    "bTbFP0": "[]",
    "bTdDD1": "[\"bTdHr1\",\"bTdHd1\",\"bTdYE1\",\"bTdZZ1\",\"bTfQD0\",\"bTdRT1\",\"bTdUH1\",\"bTdUV1\",\"bTdUf1\",\"bTdUm1\",\"bTdUt1\",\"bTdVP1\",\"bTdXJ1\",\"bTdXU1\",\"bTdXf1\",\"bTdYp1\",\"bTdZA1\",\"bTdZL1\",\"bTdaN1\",\"bTdaV1\",\"bTdag1\",\"bTfRk0\",\"bTfnJ\",\"bTfnU\",\"bTfng\",\"bTgid\",\"bTgkQ0\",\"bTgkb0\",\"bTgkj0\",\"bTgmP\",\"bTgma\",\"bTgoA\",\"bTgoL\",\"bThRi1\",\"bThRt1\",\"bTsmt0\",\"bTuHW0\",\"bTuJB\",\"bTwLd\",\"bTwLu\",\"bTwMF\",\"bTwNH0\",\"bTxEn1\",\"bTyBd\",\"bTydl\"]",
    "bTeCz1": "[\"bThHZ1\"]",
    "bTjEp1": "[\"bTjKj1\",\"bTjKR1\",\"bTjyH\",\"bTpYF3\",\"bTjMu1\",\"bTkAd\",\"bTkAl\",\"bTkHn3\",\"bTkID3\",\"bTkMF3\",\"bTkMw3\",\"bTkND3\",\"bTkNN3\",\"bTkNU3\",\"bTpXz3\",\"bTpYL3\",\"bTpZX2\",\"bTpZk2\"]",
    "bTkEZ1": "[\"bTkEb1\",\"bTkFR1\",\"bTsaC\",\"bTkEn1\",\"bTkZN\"]",
    "bTkTH1": "[\"bTkTN1\",\"bTkUK1\",\"bTkUQ1\"]",
    "bTliE2": "[\"bTliF2\",\"bTliW2\",\"bTliu2\",\"bTljj2\"]",
    "bTmRl1": "[\"bTmRn1\",\"bTmSF1\",\"bTmSL1\",\"bTmSi1\"]",
    "bTnQI1": "[\"bTnQJ1\",\"bTnRu1\",\"bTnSF1\",\"bTnSH1\"]",
    "bToby3": "[]",
    "bTqKZ0": "[\"bTqOc\",\"bTxPI0\",\"bTxPO0\",\"bTxPf0\",\"bTxPt0\",\"bTxQF0\",\"bTxRf0\",\"bTxVt0\",\"bTxWR0\",\"bTxin\",\"bTxpr\",\"bTqOj\",\"bTvRH0\",\"bTvRs0\",\"bTvTL0\",\"bTvTY0\",\"bTvTr\",\"bTxPl0\",\"bTxPz0\",\"bTxRl0\",\"bTxVz0\",\"bTxWX0\",\"bTxit\",\"bTxjL\"]",
    "bTqYR0": "[\"bTqYZ0\"]",
    "bTrBV1": "[\"bTrBX1\",\"bTrBd1\",\"bTrBo1\",\"bTrCp1\"]",
    "bTsUh1": "[\"bTsXm1\"]",
    "bTxAn1": "[\"bTxBF1\",\"bTxLd\",\"bTxMN\",\"bTxfV\",\"bTxgM1\",\"bTxfj\",\"bTxoF\",\"bTxrR\",\"bTyEF\",\"bTylS0\",\"bTxDD1\",\"bTxDN1\",\"bTxDU1\",\"bTxDb1\",\"bTxDl1\",\"bTxQu\",\"bTxcn\",\"bTxhV1\",\"bTxhg1\",\"bTxgY\",\"bTxiW\",\"bTxjx1\",\"bTxkr1\",\"bTxlF1\",\"bTxoh\",\"bTxrj\"]",
    "bTxFA1": "[]",
    "Page_standard_": "[]"
  },
  "page_name_to_id": {
    "404": "AAU",
    "index": "bTGYf",
    "reset_pw": "AAL"
  },
  "custom_name_to_id": {
    "278af74c02757b88702538b646fd2f68": {
      "name": "Signup / Login Popup",
      "custom_id": "ACq"
    },
    "bf50d5e661106d0abe925af3c2e6f7e7": {
      "name": "Header",
      "custom_id": "bTGiL"
    },
    "ded40f2a77c30efc6062db0cbd857746": {
      "name": "Footer",
      "custom_id": "bTGkE"
    }
  },
  "page_name_to_path": {
    "404": "%p3.AAX",
    "index": "%p3.bTGbC",
    "reset_pw": "%p3.AAW"
  },
};
