import { elements } from './elements/index.js';

export const gf_options = {
  "elements": elements,
  "properties": {
    "height": 68,
    "left": 2,
    "top": 63,
    "width": 87,
    "zindex": 3,
    "boxshadow_horizontal": 0,
    "border_roundness": 0,
    "boxshadow_style": "none",
    "vertical_centering": true,
    "background_style": "none",
    "bgcolor": "var(--color_surface_default)",
    "boxshadow_blur": 2,
    "boxshadow_color": "var(--color_bTHBQ_default)",
    "reference": "bTwlr",
    "fit_height": true,
    "offset_top": -4,
    "offset_left": -8,
    "padding_top": 8,
    "padding_left": 8,
    "single_width": true,
    "max_width_css": "280px",
    "min_width_css": "256px",
    "padding_right": 8,
    "single_height": false,
    "padding_bottom": 8,
    "horiz_alignment": "flex-start",
    "container_layout": "column",
    "collapse_when_hidden": true
  },
  "type": "GroupFocus",
  "id": "bTwlx",
  "default_name": "GroupFocus A",
  "name": "GF Options",
};
